### ISSUE TITLE
Number Liner

### ISSUE THREAD

**Issue by Dimusikus** [Kostelano/jCode-Syntax-Highlighter#36]
Не работает нумерация строк. ПРиходится в ручную лезть в исходный код страницы и подставлять line-numbers.
Был бы рад если подпатчили этот баг.

**Comment by Kostelano** [comment]
Добрый день! Нумерация строк работает корректно. Это особенность плагина [Line Numbers](https://prismjs.com/plugins/line-numbers).

Непосредственно параметр отвечает за подключение скрипта `line-numbers`, и реализован отдельно с целью уменьшения размера общего размера JS. Т.е. если нумерация строк не нужна - отключите параметр. Если нужна, то включите, но и дописывайте класс `line-numbers`.

**Comment by Dimusikus** [comment]
Да Здарвствуйте.
Спасибо за столь быстрый ответ.
Тогда ладно,  хотелось бы чтобы автоматом дописывался класс line-numbers.
Будем ручками дописывать куда деваться.

**Comment by Kostelano** [comment]
Код вставляется кнопкой редактора - стороннего плагина. Вариант - придумывать новый плагин (новую кнопку), который будет добавлять тег кода + класс `line-numbers`. Возможно, когда-нибудь, но не сейчас.
